### ISSUE TITLE
daxa 2.0 milestone

### ISSUE THREAD

**Issue by Ipotrick** [Ipotrick/Daxa#52]
List of todos to get daxa 2.0 out.
Daxa 2.0 is only meant to be a cleanup of the current state of daxa for a new stable release.
## General:
- [x] simplify shader integration (image handles, type sharing and makro naming)
- [x] rename Context to Instance
- [x] add all missing max enum count values
- [x] remove image aspect
- [x] add image compatibility flags (currently, we say all 3D images are 2D array compat.)
- [x] improve glsl shader image and buffer access (add defines to create own accessors that take qualifiers into account)
## Documentation:
- [x] improve readme
- [x] fix up tutorial
- [x] add function documentation for complex functions
- [ ] task graph wiki page
- [x] pipeline manager wiki page
- [x] clean up samples and tests
## TaskGraph:
- [x] rename it to TaskGraph
- [x] task list interface should give layout of used images via a function.
- [x] fix naming of TaskImageHandle and TaskBufferHandle.
- [x] make staging memory pool optional (with corresponding debug messages)
## PipelineManager:
- [x] return a variant of all possible results and remove the optional<Result<bool>> on hot reloading
- [x] make thread safe

**Comment by Ipotrick** [comment]
daxa 2.0 was released
